### ISSUE TITLE
not exporting

### ISSUE THREAD

**Issue by mrasap** [rlespinasse/docker-drawio-desktop-headless#2]
Nice work! This seems to be what I am looking for, but I can't get it to work. I might be a bit too quick, since you only released it 2 days ago. I didn't see any issue templates so I hope I have given you everything you need to know.

I don't have drawio-desktop installed on this machine. Let me know if it is a fault on my side! 

## intended use
I have a repo with UML diagrams: https://gitlab.com/powderbooking/readme/-/tree/3-uml-architecture-diagram
I would like to keep the `.drawio` data in git. In my CI/CD pipeline, I want to export those files to `.png` files and publish them as artifacts. Therefore, I want to export the `.drawio` files using a CLI that can be run inside my pipeline. This way, I do not need to store a large blob inside my repo, yet still get access to the `.png` files.

## command executed
```
git clone https://gitlab.com/powderbooking/readme.git
cd readme/img
docker run -it -v $(pwd):/data rlespinasse/drawio-desktop-headless -f png -o infra.png -x powderbooking_uml_infra.drawio
```

## expected output
a png file named `infra.png`
a log statement with `powderbooking_uml_infra.drawio -> infra.png`

## observed output
Nothing. No log statements, no file. It hangs after the given timeout window. I have also tried it with a 60s timeout.

## system used
```
$ uname -a
Linux ithilien-Aspire-V3-371 4.15.0-132-generic #136-Ubuntu SMP Tue Jan 12 14:58:42 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
$ docker -v
Docker version 20.10.2, build 2291f61
```

**Comment by rlespinasse** [comment]
First of all, Thanks for the issue report and the effort you put in it. Nice read.
(It's also remind me that I need to add issue template to this repository 😄 )

In the command executed, you need to setup the working directory to `/data`. 
The project readme miss to tell you that, so it's a bug.

In addition during the bug testing on your use case, I find another bug, the error output is not printed. 
Also a bug.

Since you need to work on multiple files in a CI/CD environment, I think https://github.com/rlespinasse/drawio-export is a better fit for your use case (`drawio-export` is build on top of `drawio-cli` which is the deprecated version of `docker-drawio-desktop-headless`).

**Comment by mrasap** [comment]
This is great, thanks! The drawio-export repo was just what I needed. Keep up the good work!

**Comment by rlespinasse** [comment]
@mrasap Thanks you for the sponsoring
