### ISSUE TITLE
Publish as arm64 image

### ISSUE THREAD

**Issue by rlespinasse** [rlespinasse/docker-drawio-desktop-headless#30]
Related to rlespinasse/drawio-export#80

**Comment by bhagyas** [comment]
Is there any updates on this?

**Comment by rlespinasse** [comment]
Since this try on #31, I didn't have time to rework on it.

**Comment by swill** [comment]
Just to provide some feedback (which is probably known).  I get the following when trying the code in an M1 environment.

```
docker run -it rlespinasse/drawio-desktop-headless:v1.7.0 --help
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 5 (Trace/breakpoint trap) - core dumped
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
```

Maybe I am not running it correctly, but figured I would post back just in case.

Thank you for all your hard work on this project.  It has been a great tool in supporting documentation automation.

**Comment by juananpe** [comment]
I tried to build drawio-desktop for arm64. The problem is that drawio depends on electron-builder-binaries

https://github.com/jgraph/drawio-desktop/blob/dev/package.json#L45

And when trying to build it on arm64 and generate a .deb, electron-builder will use fpm. The problem is that fpm doesn't have support for arm64:

See: https://github.com/electron-userland/electron-builder-binaries/issues/17
and fixing that issue is not so easy:
See: https://github.com/signalapp/Signal-Desktop/issues/6063#issuecomment-1307001166

So I was able to build drawio-desktop (arm64) but not the corresponding .deb package. 

You can find the arm64 binary of drawio-desktop here:
https://www.dropbox.com/s/zhf51bem4c18e8z/drawio-desktop-arm64.zip?dl=1

**Comment by rlespinasse** [comment]
Seem that the next release of drawio-desktop will support arm64.
I will wait to see if this new build is enough.

**Comment by rlespinasse** [comment]
Since v21.6.5, drawio desktop publish deb package on arm architecture
